# Generated by Django 4.2.7 on 2024-05-21 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_abstract_article_category_article_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('frequency', models.CharField(choices=[('immediate', 'An email at the moment a new article gets published'), ('monthly', "A monthly email regarding the summary of the month's new articles")], max_length=10)),
            ],
        ),
    ]
